INSERT INTO USER VALUES ('USER1', 25,'MALE','HYDERABAD'); 
INSERT INTO USER VALUES ('USER2', 26,'FEMALE','BANGALORE'); 
INSERT INTO USER VALUES ('USER3', 23,'MALE','CHENNAI'); 
INSERT INTO USER VALUES ('USER4', 27,'MALE','MUMBAI');  
 